# generates the parser with 'tree-sitter generate' if the parser is out of date
name: Generate Parser

on:
  push:
    branches:
      - main
jobs:
  generate:
    name: Generate Parser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        run: npm ci

      - name: Generate parser files
        run: |
          npx tree-sitter generate
          npx tree-sitter build-wasm

      - name: Commit generated parser files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate parser
          file_pattern: src *.wasm
